require 'solidruby/version'
require 'solidruby/bill_of_material'
require 'solidruby/solidruby_object'
require 'solidruby/primitive'
require 'solidruby/assembly'
require 'solidruby/hardware'
require 'solidruby/rubyscad_bridge'

require 'solidruby/linear_bearing'
require 'solidruby/gear'
require 'solidruby/screw_thread'
require 'solidruby/printed_thread'
require 'solidruby/pipe'
require 'solidruby/ruler'
require 'solidruby/extra'

require 'solidruby/solidruby'
